### ISSUE TITLE
Access rootScope?

### ISSUE THREAD

**Issue by standingwave** [YannickDot/ngDebug#2]
I've been using ngDebug for a few days, it's an incredibly useful tool, but is there a way to access the rootScope?  It seems like there should be but it's certainly not obvious to me how to do so.

**Comment by YannickDot** [comment]
Yes, you can access the rootScope by inspecting the scope of the html element of your page. 
I've just added a method so you can inspect it easily using 
    ```
    $A.rootScope();
    ```

**Comment by standingwave** [comment]
Sweet.  Thanks for the info and adding the helper method.

**Comment by YannickDot** [comment]
You are welcome :-)
